stages:
  - build
  - deploy

variables:
  # ID do seu app no Amplify
  AMPLIFY_APP_ID: "d2eoorv54u1tcl"
  # Nome da branch que você quer que o deploy afete no Amplify.
  AMPLIFY_BRANCH_NAME: "developer"

build_frontend:
  stage: build
  image: node:20-alpine
  tags:
    - docker # Garante que vai usar o nosso runner na EC2
  script:
    - echo "Instalando dependências..."
    - npm install
    - echo "Compilando o projeto frontend..."
    - npm run build
    - echo "Compactando os artefatos de build..."
    - zip -r deploy.zip .next public package.json
  artifacts:
    paths:
      - deploy.zip # Salva o arquivo deploy.zip para o próximo estágio

deploy_to_amplify:
  stage: deploy
  image: amazon/aws-cli:latest
  tags:
    - docker
  script:
    - echo "Iniciando o deploy para o AWS Amplify..."
    - aws amplify start-deployment --app-id $AMPLIFY_APP_ID --branch-name $AMPLIFY_BRANCH_NAME --source-url deploy.zip
    - echo "Deploy enviado para o Amplify com sucesso."
  rules:
    - if: '$CI_COMMIT_BRANCH == "developer" || $CI_COMMIT_BRANCH == "test/pipeline-amplify"'
